
package Gui;

public class Panta_Online_HostLobbie extends javax.swing.JFrame {

    /**
     * Creates new form Panta_Online_HostLobbie
     */
    public Panta_Online_HostLobbie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSkinNaranja = new javax.swing.JButton();
        btnSkinAzul = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSkinVerde = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSkinRosa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btnSkinVerde1 = new javax.swing.JButton();
        btnSkinNaranja1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel1.setBackground(new java.awt.Color(13, 13, 32));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 700));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 255, 79));
        jLabel1.setText("Seleccion de Mapa");

        jButton1.setBackground(new java.awt.Color(237, 17, 101));
        jButton1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(16, 16, 32));
        jButton1.setText("Mapa1");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSkinNaranja.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinNaranja.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinNaranja.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinNaranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/EarthHeadLEFT.png"))); // NOI18N
        btnSkinNaranja.setBorder(null);
        btnSkinNaranja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinNaranjaActionPerformed(evt);
            }
        });

        btnSkinAzul.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinAzul.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinAzul.setForeground(new java.awt.Color(16, 16, 60));
        btnSkinAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BlueHeadLEFT.png"))); // NOI18N
        btnSkinAzul.setBorder(null);
        btnSkinAzul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinAzulActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 255, 79));
        jLabel2.setText("BIENVENIDO AL LOBBY");

        btnSkinVerde.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinVerde.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinVerde.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/GraduatedHeadRIGHT.png"))); // NOI18N
        btnSkinVerde.setBorder(null);
        btnSkinVerde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinVerdeActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(237, 17, 101));
        jButton9.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(16, 16, 32));
        jButton9.setText("Mapa2");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(54, 54, 133));
        jButton6.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(237, 17, 101));
        jButton6.setText("<- Atras");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 255, 79));
        jLabel4.setText("Elija una skin");

        btnSkinRosa.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinRosa.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinRosa.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinRosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PinkHeadRIGHT.png"))); // NOI18N
        btnSkinRosa.setBorder(null);
        btnSkinRosa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinRosaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(126, 45, 253));
        jButton2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(230, 255, 79));
        jButton2.setText("INICIAR");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(237, 17, 101));
        jButton10.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(16, 16, 32));
        jButton10.setText("Mapa3");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(237, 17, 101));
        jButton11.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(16, 16, 32));
        jButton11.setText("Mapa4");
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        btnSkinVerde1.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinVerde1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinVerde1.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinVerde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/GreenHeadRIGHT.png"))); // NOI18N
        btnSkinVerde1.setBorder(null);
        btnSkinVerde1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinVerde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinVerde1ActionPerformed(evt);
            }
        });

        btnSkinNaranja1.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinNaranja1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinNaranja1.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinNaranja1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/YellowHeadLEFT.png"))); // NOI18N
        btnSkinNaranja1.setBorder(null);
        btnSkinNaranja1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinNaranja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinNaranja1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("AQUI VA EL CHAT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSkinRosa, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSkinVerde1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSkinVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSkinNaranja1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSkinAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSkinNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton6)
                .addGap(96, 96, 96)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSkinAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSkinRosa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSkinVerde1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(btnSkinNaranja1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSkinVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSkinNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jButton2)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controladores.HostLobbie_Controlador.eventIniciar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSkinRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinRosaActionPerformed
        controladores.HostLobbie_Controlador.selec_Skin2();
    }//GEN-LAST:event_btnSkinRosaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        controladores.HostLobbie_Controlador.eventVolverAlMenu();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSkinVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinVerdeActionPerformed
        controladores.HostLobbie_Controlador.selec_Skin5();
    }//GEN-LAST:event_btnSkinVerdeActionPerformed

    private void btnSkinAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinAzulActionPerformed
        controladores.HostLobbie_Controlador.selec_Skin4();
    }//GEN-LAST:event_btnSkinAzulActionPerformed

    private void btnSkinNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinNaranjaActionPerformed
        controladores.HostLobbie_Controlador.selec_Skin5();
    }//GEN-LAST:event_btnSkinNaranjaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controladores.HostLobbie_Controlador.selec_Mapa1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        controladores.HostLobbie_Controlador.selec_Mapa2();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        controladores.HostLobbie_Controlador.selec_Mapa3();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        controladores.HostLobbie_Controlador.selec_Mapa4();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnSkinVerde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinVerde1ActionPerformed
        controladores.HostLobbie_Controlador.selec_Skin1();
    }//GEN-LAST:event_btnSkinVerde1ActionPerformed

    private void btnSkinNaranja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinNaranja1ActionPerformed
        controladores.HostLobbie_Controlador.selec_Skin3();
    }//GEN-LAST:event_btnSkinNaranja1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkinAzul;
    private javax.swing.JButton btnSkinNaranja;
    private javax.swing.JButton btnSkinNaranja1;
    private javax.swing.JButton btnSkinRosa;
    private javax.swing.JButton btnSkinVerde;
    private javax.swing.JButton btnSkinVerde1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
