
package Gui;

public class Panta_Online_ClienteLobbie extends javax.swing.JFrame {

    /**
     * Creates new form Panta_Online_ClienteLobbie
     */
    public Panta_Online_ClienteLobbie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        btnSkinRosa = new javax.swing.JButton();
        btnSkinNaranja = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnSkinAzul = new javax.swing.JButton();
        btnSkinVerde = new javax.swing.JButton();
        btn_casco = new javax.swing.JButton();
        btn_gorrito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(126, 45, 253));
        jButton2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(230, 255, 79));
        jButton2.setText("INICIAR");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 190, 40));

        btnSkinRosa.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinRosa.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinRosa.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinRosa.setBorder(null);
        btnSkinRosa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinRosa.setOpaque(false);
        btnSkinRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinRosaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkinRosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 230, 130, 150));

        btnSkinNaranja.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinNaranja.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinNaranja.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinNaranja.setBorder(null);
        btnSkinNaranja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinNaranja.setOpaque(false);
        btnSkinNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinNaranjaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkinNaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 276, 140, 120));

        jButton6.setBackground(new java.awt.Color(13, 13, 59));
        jButton6.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(230, 255, 79));
        jButton6.setText("<- Atras");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        btnSkinAzul.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinAzul.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinAzul.setForeground(new java.awt.Color(16, 16, 60));
        btnSkinAzul.setBorder(null);
        btnSkinAzul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinAzul.setOpaque(false);
        btnSkinAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinAzulActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkinAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, 120));

        btnSkinVerde.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinVerde.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinVerde.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinVerde.setBorder(null);
        btnSkinVerde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinVerde.setOpaque(false);
        btnSkinVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinVerdeActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkinVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 120, 130));

        btn_casco.setBackground(new java.awt.Color(13, 13, 60));
        btn_casco.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btn_casco.setForeground(new java.awt.Color(16, 16, 32));
        btn_casco.setBorder(null);
        btn_casco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_casco.setOpaque(false);
        btn_casco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cascoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_casco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 395, 140, 150));

        btn_gorrito.setBackground(new java.awt.Color(13, 13, 60));
        btn_gorrito.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btn_gorrito.setForeground(new java.awt.Color(16, 16, 32));
        btn_gorrito.setBorder(null);
        btn_gorrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_gorrito.setOpaque(false);
        btn_gorrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gorritoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gorrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 394, 140, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Skin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -25, 700, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkinRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinRosaActionPerformed
        controladores.ClienteLobbie_Controlador.selec_Skin2();
    }//GEN-LAST:event_btnSkinRosaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controladores.ClienteLobbie_Controlador.eventIniciar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSkinNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinNaranjaActionPerformed
        controladores.ClienteLobbie_Controlador.selec_Skin3();
    }//GEN-LAST:event_btnSkinNaranjaActionPerformed

    private void btnSkinAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinAzulActionPerformed
        controladores.ClienteLobbie_Controlador.selec_Skin4();
    }//GEN-LAST:event_btnSkinAzulActionPerformed

    private void btnSkinVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinVerdeActionPerformed
        controladores.ClienteLobbie_Controlador.selec_Skin1();
    }//GEN-LAST:event_btnSkinVerdeActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        controladores.ClienteLobbie_Controlador.eventVolverAlMenu();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_gorritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gorritoActionPerformed
        controladores.ClienteLobbie_Controlador.selec_Skin6();
    }//GEN-LAST:event_btn_gorritoActionPerformed

    private void btn_cascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cascoActionPerformed
        controladores.ClienteLobbie_Controlador.selec_Skin5();
    }//GEN-LAST:event_btn_cascoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkinAzul;
    private javax.swing.JButton btnSkinNaranja;
    private javax.swing.JButton btnSkinRosa;
    private javax.swing.JButton btnSkinVerde;
    private javax.swing.JButton btn_casco;
    private javax.swing.JButton btn_gorrito;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
