
package Gui;

public class Panta_Online_HostLobbie extends javax.swing.JFrame {

    /**
     * Creates new form Panta_Online_HostLobbie
     */
    public Panta_Online_HostLobbie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        btnSkinRosa = new javax.swing.JButton();
        btnSkinVerde = new javax.swing.JButton();
        btnSkinAzul = new javax.swing.JButton();
        btnSkinGorrito = new javax.swing.JButton();
        btnSkinNaranja = new javax.swing.JButton();
        btnSkinCasco = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel3.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(13, 13, 59));
        jButton6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(230, 255, 79));
        jButton6.setText("<- Atras");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        btnSkinRosa.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinRosa.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinRosa.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinRosa.setBorder(null);
        btnSkinRosa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinRosa.setOpaque(false);
        btnSkinRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinRosaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSkinRosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 130, 60));

        btnSkinVerde.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinVerde.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinVerde.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinVerde.setBorder(null);
        btnSkinVerde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinVerde.setOpaque(false);
        btnSkinVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinVerdeActionPerformed(evt);
            }
        });
        jPanel3.add(btnSkinVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 175, 140, 130));

        btnSkinAzul.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinAzul.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinAzul.setForeground(new java.awt.Color(16, 16, 60));
        btnSkinAzul.setBorder(null);
        btnSkinAzul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinAzul.setOpaque(false);
        btnSkinAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinAzulActionPerformed(evt);
            }
        });
        jPanel3.add(btnSkinAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 110, 70));

        btnSkinGorrito.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinGorrito.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinGorrito.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinGorrito.setBorder(null);
        btnSkinGorrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinGorrito.setOpaque(false);
        btnSkinGorrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinGorritoActionPerformed(evt);
            }
        });
        jPanel3.add(btnSkinGorrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 120, 80));

        btnSkinNaranja.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinNaranja.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinNaranja.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinNaranja.setBorder(null);
        btnSkinNaranja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinNaranja.setOpaque(false);
        btnSkinNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinNaranjaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSkinNaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 130, 120));

        btnSkinCasco.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinCasco.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinCasco.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinCasco.setBorder(null);
        btnSkinCasco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinCasco.setOpaque(false);
        btnSkinCasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinCascoActionPerformed(evt);
            }
        });
        jPanel3.add(btnSkinCasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 246, 110, 130));

        jButton2.setBackground(new java.awt.Color(126, 77, 181));
        jButton2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(230, 255, 79));
        jButton2.setText("INICIAR");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 360, 40));

        jButton1.setBackground(new java.awt.Color(237, 17, 101));
        jButton1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(16, 16, 32));
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 127, 130));

        jButton9.setBackground(new java.awt.Color(237, 17, 101));
        jButton9.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(16, 16, 32));
        jButton9.setBorder(null);
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 127, 130));

        jButton10.setBackground(new java.awt.Color(237, 17, 101));
        jButton10.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(16, 16, 32));
        jButton10.setBorder(null);
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 450, 125, 130));

        jButton11.setBackground(new java.awt.Color(237, 17, 101));
        jButton11.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(16, 16, 32));
        jButton11.setBorder(null);
        jButton11.setOpaque(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 130, 130));

        jLabel3.setBackground(new java.awt.Color(0, 255, 0));
        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Boton chat");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/SM.jpg"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 700, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controladores.Controlador_Host.eventIniciar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSkinRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinRosaActionPerformed
        controladores.Controlador_Host.selec_Skin2();
    }//GEN-LAST:event_btnSkinRosaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        controladores.Controlador_Host.eventVolverAlPre();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSkinGorritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinVerdeActionPerformed
        controladores.Controlador_Host.selec_Skin5();
    }//GEN-LAST:event_btnSkinVerdeActionPerformed

    private void btnSkinAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinAzulActionPerformed
        controladores.Controlador_Host.selec_Skin4();
    }//GEN-LAST:event_btnSkinAzulActionPerformed

    private void btnSkinCascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinNaranjaActionPerformed
        controladores.Controlador_Host.selec_Skin5();
    }//GEN-LAST:event_btnSkinNaranjaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controladores.Controlador_Host.selec_Mapa1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        controladores.Controlador_Host.selec_Mapa2();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        controladores.Controlador_Host.selec_Mapa3();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        controladores.Controlador_Host.selec_Mapa4();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnSkinVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinVerde1ActionPerformed
        controladores.Controlador_Host.selec_Skin1();
    }//GEN-LAST:event_btnSkinVerde1ActionPerformed

    private void btnSkinNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinNaranja1ActionPerformed
        controladores.Controlador_Host.selec_Skin3();
    }//GEN-LAST:event_btnSkinNaranja1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkinAzul;
    private javax.swing.JButton btnSkinCasco;
    private javax.swing.JButton btnSkinGorrito;
    private javax.swing.JButton btnSkinNaranja;
    private javax.swing.JButton btnSkinRosa;
    private javax.swing.JButton btnSkinVerde;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
