package Gui;

public class Panta_Lobbie extends javax.swing.JFrame {

    /**
     * Creates new form Panta_Lobbie
     */
    public Panta_Lobbie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnSkinAzul = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnSkinRosa = new javax.swing.JButton();
        btnSkinVerde = new javax.swing.JButton();
        btnSkinGorrito = new javax.swing.JButton();
        btnSkinNaranja1 = new javax.swing.JButton();
        btnSkinCasco = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 700));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSkinAzul.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinAzul.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinAzul.setForeground(new java.awt.Color(16, 16, 60));
        btnSkinAzul.setBorder(null);
        btnSkinAzul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinAzul.setOpaque(false);
        btnSkinAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinAzulActionPerformed(evt);
            }
        });
        jPanel2.add(btnSkinAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 110, 60));

        jButton6.setBackground(new java.awt.Color(13, 13, 59));
        jButton6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(126, 77, 181));
        jButton6.setText("<- Atras");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        btnSkinRosa.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinRosa.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinRosa.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinRosa.setBorder(null);
        btnSkinRosa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinRosa.setOpaque(false);
        btnSkinRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinRosaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSkinRosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 325, 150, 50));

        btnSkinVerde.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinVerde.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinVerde.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinVerde.setBorder(null);
        btnSkinVerde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinVerde.setOpaque(false);
        btnSkinVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinVerdeActionPerformed(evt);
            }
        });
        jPanel2.add(btnSkinVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 130, 130));

        btnSkinGorrito.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinGorrito.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinGorrito.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinGorrito.setBorder(null);
        btnSkinGorrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinGorrito.setOpaque(false);
        btnSkinGorrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinGorritoActionPerformed(evt);
            }
        });
        jPanel2.add(btnSkinGorrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 140, 80));

        btnSkinNaranja1.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinNaranja1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinNaranja1.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinNaranja1.setBorder(null);
        btnSkinNaranja1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinNaranja1.setOpaque(false);
        btnSkinNaranja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinNaranja1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSkinNaranja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, 100));

        btnSkinCasco.setBackground(new java.awt.Color(13, 13, 60));
        btnSkinCasco.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnSkinCasco.setForeground(new java.awt.Color(16, 16, 32));
        btnSkinCasco.setBorder(null);
        btnSkinCasco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkinCasco.setOpaque(false);
        btnSkinCasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkinCascoActionPerformed(evt);
            }
        });
        jPanel2.add(btnSkinCasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 120, 130));

        jButton1.setBackground(new java.awt.Color(237, 17, 101));
        jButton1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(16, 16, 32));
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 440, 120, 130));

        jButton9.setBackground(new java.awt.Color(237, 17, 101));
        jButton9.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(16, 16, 32));
        jButton9.setBorder(null);
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 127, 130));

        jButton2.setBackground(new java.awt.Color(126, 77, 181));
        jButton2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(230, 255, 79));
        jButton2.setText("INICIAR");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 313, 40));

        jButton11.setBackground(new java.awt.Color(237, 17, 101));
        jButton11.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(16, 16, 32));
        jButton11.setBorder(null);
        jButton11.setOpaque(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 440, 127, 130));

        jButton12.setBackground(new java.awt.Color(237, 17, 101));
        jButton12.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(16, 16, 32));
        jButton12.setBorder(null);
        jButton12.setOpaque(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 440, 120, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/SM.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        controladores.Lobbie_Controlador.eventVolverAlMenu();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controladores.Lobbie_Controlador.eventIniciar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSkinVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinVerdeActionPerformed
        controladores.Lobbie_Controlador.selec_Skin1();
    }//GEN-LAST:event_btnSkinVerdeActionPerformed

    private void btnSkinRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinRosaActionPerformed
        controladores.Lobbie_Controlador.selec_Skin2();
    }//GEN-LAST:event_btnSkinRosaActionPerformed

    private void btnSkinAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinAzulActionPerformed
        controladores.Lobbie_Controlador.selec_Skin4();
    }//GEN-LAST:event_btnSkinAzulActionPerformed

    private void btnSkinCascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinCascoActionPerformed
        controladores.Lobbie_Controlador.selec_Skin5();
    }//GEN-LAST:event_btnSkinCascoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controladores.Lobbie_Controlador.selec_Mapa1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        controladores.Lobbie_Controlador.selec_Mapa2();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        controladores.Lobbie_Controlador.selec_Mapa3();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        controladores.Lobbie_Controlador.selec_Mapa4();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnSkinGorritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinGorritoActionPerformed
        controladores.Lobbie_Controlador.selec_Skin6();
    }//GEN-LAST:event_btnSkinGorritoActionPerformed

    private void btnSkinNaranja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkinNaranja1ActionPerformed
        controladores.Lobbie_Controlador.selec_Skin3();
    }//GEN-LAST:event_btnSkinNaranja1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkinAzul;
    private javax.swing.JButton btnSkinCasco;
    private javax.swing.JButton btnSkinGorrito;
    private javax.swing.JButton btnSkinNaranja1;
    private javax.swing.JButton btnSkinRosa;
    private javax.swing.JButton btnSkinVerde;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
